### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by tw4452852** [telegex/telegex#29]
Here's log:

```
18:22:45.140 [notice] Application notifier_bot exited: NotifierBot.Application.start(:normal, []) returned an error: shutdown: failed to start child: NotifierBot.HookHandler
    ** (EXIT) shutdown: failed to start child: {Bandit, #Reference<0.2119600828.1676148737.158249>}
        ** (EXIT) an exception was raised:
            ** (UndefinedFunctionError) function Telegex.Hook.Server.init/1 is undefined (module Telegex.Hook.Server is not available)
                Telegex.Hook.Server.init(%{secret_token: "123456", on_update: #Function<0.31120284/1 in NotifierBot.HookHandler.on_update>})
                (bandit 0.7.7) lib/bandit.ex:391: Bandit.plug/1
                (bandit 0.7.7) lib/bandit.ex:317: Bandit.start_link/1
                (stdlib 5.0.2) supervisor.erl:420: :supervisor.do_start_child_i/3
                (stdlib 5.0.2) supervisor.erl:406: :supervisor.do_start_child/2
                (stdlib 5.0.2) supervisor.erl:390: anonymous fn/3 in :supervisor.start_children/2
                (stdlib 5.0.2) supervisor.erl:1256: :supervisor.children_map/4
                (stdlib 5.0.2) supervisor.erl:350: :supervisor.init_children/2
Kernel pid terminated (application_controller) ({application_start_failure,notifier_bot,{{shutdown,{failed_to_start_child,'Elixir.NotifierBot.HookHandler',{shutdown,{failed_to_start_child,{'Elixir.Bandit',#Ref<0.2119600828.1676148737.158249>},{'EXIT',{und
ef,[{'Elixir.Telegex.Hook.Server',init,[#{secret_token => <<"123456">>,on_update => #Fun<Elixir.NotifierBot.HookHandler.0.31120284>}],[]},{'Elixir.Bandit',plug,1,[{file,"lib/bandit.ex"},{line,391}]},{'Elixir.Bandit',start_link,1,[{file,"lib/bandit.ex"},{$
ine,317}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,420}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,406}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,390}]},{supervisor,children_map,4,[{
file,"supervisor.erl"},{line,1256}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,350}]}]}}}}}},{'Elixir.NotifierBot.Application',start,[normal,[]]}}})
```

**Comment by Hentioe** [comment]
Have you added plug in the deps?  If not, please add it. If it has been added, please try to delete _build dir and rebuild.

**Comment by tw4452852** [comment]
`Plug` is in the deps, after cleanning the `_build` directory, the issue gone.
BTW, I'm curious if this issue is related to the cache or the code loading order?

**Comment by Hentioe** [comment]
I know the reason, but I can't solve this phenomenon yet because I don't fully understand something.

The `Telegex.Hook.Server` module will detect whether the `Plug` module is loaded when compiling. If not, it will not be compiled. Because you upgraded Telegex (`Telegex.Hook.Server` module code was modified), but the local Plug build cache is still used, which causes the `Plug` not to be loaded during compilation, so the `Telegex.Hook.Server` module will not be compiled.

So deleting `_build/dev/lib/plug` to trigger recompilation of Plug can solve this problem.

**Comment by tw4452852** [comment]
Thanks @Hentioe for the explaination. After removing the `_build` directory, this issue disappeared.
