### ISSUE TITLE
compile error for sample project

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [telegex/telegex#38]
hi, i made a sample project, but not working.

```sh
mix new demo
```

add deps

```elixir
{:telegex, "~> 1.8.0"},
```

config/config.exs

```elixir
import Config

config :demo, mode: config_env()
import_config "#{config_env()}.exs"
```

config/config.dev.exs

```elixir
import Config

config :telegex,
  token: "xxxxxxxxxxx"
```

run

```sh
mix deps.get
iex -S mix
```

```sh
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Compiling 1 file (.ex)
Generated demo app

11:59:09.914 [notice] Application telegex exited: exited in: Telegex.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) The module Finch was given as a child to a supervisor but it does not exist
            (elixir 1.17.2) lib/supervisor.ex:797: Supervisor.init_child/1
            (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
            (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
            (elixir 1.17.2) lib/supervisor.ex:783: Supervisor.init/2
            (elixir 1.17.2) lib/supervisor.ex:707: Supervisor.start_link/2
            (kernel 10.0.1) application_master.erl:295: :application_master.start_it_old/4

11:59:09.919 [notice] Application jason exited: :stopped

11:59:09.919 [notice] Application typed_struct exited: :stopped
```

**Comment by Hentioe** [comment]
add [`finch`](https://hex.pm/packages/finch) to deps, which is the HTTP API caller.

**Comment by ziyouchutuwenwu** [comment]
thank you very much, and is there any way to support global proxy option?

**Comment by Hentioe** [comment]
As far as I know, HTTPoison supports configuring sockes5 proxy. You can configure `caller_adapter` as HTTPoison and pass proxy related options.

**Comment by ziyouchutuwenwu** [comment]
it works! thank you very much!
